name: Tests

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php-versions: [ 8.4 ]
        laravel-versions: [ 11, 12 ]

    name: PHP ${{ matrix.php-versions }} - Laravel ${{ matrix.laravel-versions }} - ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
        extensions: intl, fileinfo

    - name: Install dependencies (Laravel 11)
      if: matrix.laravel-versions == 11
      run: composer require "orchestra/testbench:^9.0" --no-update --dev

    - name: Install dependencies (Laravel 12)
      if: matrix.laravel-versions == 12
      run: composer require "orchestra/testbench:^10.0" --no-update --dev

    - name: Update dependencies
      run: composer update --prefer-dist --no-progress --no-interaction

    - name: Run Test Suite
      run: composer run test
